[toolchain]

[features]
seeds = false
skip-lint = false

[programs.localnet]
staker = "4Xi45X7QeEybUF5g1Dhu81BTeXz6Z6VSHveJqsg5uT5J"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "https://solana-devnet.g.alchemy.com/v2/DKkLcxzy5RTawxngi9lQRS5YWISvgt28"
wallet = "~/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
